use_frameworks!

platform :ios, '10.0'

target 'TXTransitionSwift_Example' do
  pod 'TXTransitionSwift', :path => '../'

  target 'TXTransitionSwift_Tests' do
    inherit! :search_paths

    
  end
end
